name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build and test libffi on cygwin
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: wget gcc-core make dejagnu automake autoconf libtool texinfo dos2unix unzip

      - run: |
          cd $(cygpath $RUNNER_WORKSPACE)/libffi
          wget https://rl.gl/cli/rlgl-windows-amd64.zip
          unzip rlgl-windows-amd64.zip
          find . -name \*.m4|xargs dos2unix
          find . -name \*.ac|xargs dos2unix
          find . -name \*.am|xargs dos2unix
          find . -name \*.host|xargs dos2unix
          autoreconf -f -v -i
          ./configure
          find . -name libtool\*|xargs dos2unix
          make -j 4
          make check || true
          ./rlgl/rlgl.exe l --key=0LIBFFI-0LIBFFI-0LIBFFI-0LIBFFI https://rl.gl
          ID=$(./rlgl/rlgl.exe start)
          ./rlgl/rlgl.exe e --id=$ID --policy=https://github.com/libffi/rlgl-policy.git $(find . -name libffi.log)
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

  build-msvc:
    name: Build and test libffi with Visual C++
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.8.1
      - uses: microsoft/setup-msbuild@v1.0.2

      - name: Build and test
        run: |
          C:\tools\cygwin\bin\bash.exe -lc "(cd $(cygpath $RUNNER_WORKSPACE)/libffi; ./autogen.sh)"
          C:\tools\cygwin\bin\bash.exe -lc "(cd $(cygpath $RUNNER_WORKSPACE)/libffi; ./configure CC='$(cygpath $RUNNER_WORKSPACE)/libffi/msvcc.sh)' CXX='$(cygpath $RUNNER_WORKSPACE)/libffi/msvcc.sh)' LD='link' CPP='cl -nologo -EP' CXXCPP='cl -nologo -EP' CPPFLAGS='-DFFI_BUILDING_DLL' AR='$(cygpath $RUNNER_WORKSPACE)/libffi/.travis/ar-lib lib' NM='dumpbin -symbols' STRIP=':' --build=$BUILD --host=$HOST $DEBUG_ARG $SHARED_ARG)"
        shell: cmd
