name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build and test on ${{ matrix.distro }} ${{ matrix.arch }}
    runs-on: ubuntu-latest

    # Run steps on a matrix of 3 arch/distro combinations
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: fedora_latest
          - arch: ppc64le
            distro: fedora_latest
          - arch: s390x
            distro: fedora_latest

    steps:
      - uses: actions/checkout@v2

      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*|jessie|stretch|buster|bullseye)
                apt-get update -q -y
                apt-get install -q -y wget gcc dejagnu automake autoconf texinfo
                ;;
              fedora*)
                dnf -y update
                dnf -y install wget gcc dejagnu automake autoconf texinfo
                ;;
              alpine*)
                apk update
                apk add wget gcc dejagnu automake autoconf texinfo
                ;;
            esac
          run: |
            HOST=${{ matrix.arch }}-linux-gnu OS_NAME=linux ./.travis/install.sh
            HOST=${{ matrix.arch }}-linux-gnu OS_NAME=linux ./.travis/build.sh
